#!/usr/bin/env python3
"""
Checksum every raw study file, so any change to read-only data is detectable.

The raw data is too large for git (3.6 GB, ~32k binary files) and is not ours to
publish. Instead we commit a SHA-256 of every file. That gives the thing version
control was actually wanted for: proof of whether a raw file changed, and which
one -- without storing the bytes.

    write   build checksums/raw_sha256.txt         (first run, or after the lab
                                                    sends genuinely new scans)
    verify  re-hash and diff against the committed file

`verify` is the one to run before and after any cleanup work.

Usage:
    .venv/bin/python src/checksum_raw.py write
    .venv/bin/python src/checksum_raw.py verify
"""
from __future__ import annotations

import argparse
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTFILE = os.path.join(ROOT, "checksums", "raw_sha256.txt")

# Raw study data only. Project files (src/, derived/, docs) belong in git and are
# deliberately NOT checksummed here. Session folders are matched by SESSION_RE;
# add loose files (spreadsheets, exports) via the EXTRA_RAW_FILES env var.

SESSION_RE = re.compile(r"^\d{4}(\s|$)")
EXTRA_RAW = [p for p in os.environ.get("EXTRA_RAW_FILES", "").split(os.pathsep) if p]
SKIP_NAMES = {".DS_Store"}


def raw_files() -> list[str]:
    out = []
    for name in sorted(os.listdir(ROOT)):
        p = os.path.join(ROOT, name)
        if os.path.isdir(p) and SESSION_RE.match(name):
            for dirpath, dirnames, filenames in os.walk(p):
                dirnames.sort()
                for fn in sorted(filenames):
                    if fn in SKIP_NAMES:
                        continue
                    out.append(os.path.relpath(os.path.join(dirpath, fn), ROOT))
        elif name in EXTRA_RAW and os.path.isfile(p):
            out.append(name)
    return out


def sha256(path: str, buf: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        while chunk := fh.read(buf):
            h.update(chunk)
    return h.hexdigest()


def compute(paths: list[str]) -> dict[str, str]:
    out = {}
    for i, rel in enumerate(paths, 1):
        out[rel] = sha256(os.path.join(ROOT, rel))
        if i % 2000 == 0:
            print(f"  hashed {i}/{len(paths)}", flush=True)
    return out


def load(path: str) -> dict[str, str]:
    d = {}
    with open(path) as fh:
        for ln in fh:
            ln = ln.rstrip("\n")
            if not ln or ln.startswith("#"):
                continue
            digest, rel = ln.split("  ", 1)
            d[rel] = digest
    return d


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("action", choices=["write", "verify"])
    args = ap.parse_args()

    paths = raw_files()
    total = sum(os.path.getsize(os.path.join(ROOT, p)) for p in paths)
    print(f"{len(paths)} raw files, {total / 1e9:.2f} GB")

    if args.action == "write":
        if os.path.exists(OUTFILE):
            print(f"\n{OUTFILE} already exists.\n"
                  "Overwriting it would erase the baseline you verify against.\n"
                  "Delete it explicitly first if that is really what you want.")
            sys.exit(1)
        os.makedirs(os.path.dirname(OUTFILE), exist_ok=True)
        digests = compute(paths)
        with open(OUTFILE, "w") as fh:
            fh.write("# SHA-256 of every raw study file. Generated by "
                     "src/checksum_raw.py.\n")
            fh.write("# Verify with: .venv/bin/python src/checksum_raw.py verify\n")
            for rel in sorted(digests):
                fh.write(f"{digests[rel]}  {rel}\n")
        print(f"\nwrote {OUTFILE}  ({os.path.getsize(OUTFILE) / 1e6:.1f} MB)")
        print("Commit this file. It is the baseline.")
        return

    if not os.path.exists(OUTFILE):
        sys.exit(f"no baseline at {OUTFILE}; run 'write' first")
    old = load(OUTFILE)
    new = compute(paths)

    missing = sorted(set(old) - set(new))
    added = sorted(set(new) - set(old))
    changed = sorted(p for p in set(old) & set(new) if old[p] != new[p])

    print()
    if not (missing or added or changed):
        print(f"OK — all {len(new)} raw files unchanged.")
        return

    if missing:
        print(f"!! {len(missing)} MISSING (deleted or renamed):")
        for p in missing[:20]:
            print(f"     {p}")
        if len(missing) > 20:
            print(f"     ... and {len(missing) - 20} more")
    if changed:
        print(f"!! {len(changed)} MODIFIED:")
        for p in changed[:20]:
            print(f"     {p}")
        if len(changed) > 20:
            print(f"     ... and {len(changed) - 20} more")
    if added:
        print(f"   {len(added)} new files (fine if the lab sent more scans):")
        for p in added[:20]:
            print(f"     {p}")
        if len(added) > 20:
            print(f"     ... and {len(added) - 20} more")
    print("\nRaw data is supposed to be read-only. Missing or modified files mean\n"
          "something wrote to it -- restore from the pristine archive before\n"
          "trusting any downstream number.")
    sys.exit(1)


if __name__ == "__main__":
    main()
